apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: jain-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: prod/jainapp/postgres
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/jainapp/postgres
        property: password

    - secretKey: DB_HOST
      remoteRef:
        key: prod/jainapp/postgres
        property: host

    - secretKey: DB_NAME
      remoteRef:
        key: prod/jainapp/postgres
        property: database